import React, { useState } from 'react';
import Moment from 'react-moment';

import { CareerHistory as history } from './data-points';

// **** START: Material-ui 

import { Card, Typography, Container, Box, CardContent, Grid } from '@material-ui/core';
import { makeStyles } from '@material-ui/core/styles';

// Expansion panel
import ExpansionPanel from '@material-ui/core/ExpansionPanel';
import ExpansionPanelSummary from '@material-ui/core/ExpansionPanelSummary';
import ExpansionPanelDetails from '@material-ui/core/ExpansionPanelDetails';

import Avatar from '@material-ui/core/Avatar';

// **** End: Material-ui 


// react-Icons
import { MdExpandMore } from 'react-icons/md';
import { AiOutlineUsergroupAdd, AiOutlineUsergroupDelete } from 'react-icons/ai';
import { BsKanban } from 'react-icons/bs';
// react-html-parser
import parse from 'html-react-parser';


const useStyles = makeStyles((theme) => ({
    root: {
        width: '100%',
    },
    heading: {
        fontSize: theme.typography.pxToRem(15),
        fontWeight: theme.typography.fontWeightRegular,
        flexBasis: '33.33%',
        flexShrink: 0,
    },
    secondaryHeading: {
        fontSize: theme.typography.pxToRem(15),
        // color: theme.palette.text.secondary,
        color: 'grey',
    },
    /* Palette generated by Material Palette - materialpalette.com/indigo/blue-grey */

    darkPrimaryColor: { background: '#303F9F' },
    defaultPrimaryColor: { background: '#3F51B5' },
    lightPrimaryColor: { background: '#C5CAE9' },
    textPrimaryColor: { color: '#FFFFFF' },
    accentColor: { background: '#607D8B' },
    primaryTextColor: { color: '#212121' },
    secondaryTextColor: { color: '#757575' },
    dividerColor: { borderColor: '#BDBDBD' },


}));
// End Material-ui Expansion Panel   




const CareerHistory = () => {

    // Material UI expanded
    const classes = useStyles();
    const [expanded, setExpanded] = useState(false);
    const handleChange = (panel) => (event, isExpanded) => {
        setExpanded(isExpanded ? panel : false);
    };


    const sortedContent = history.sort()

    // Render employment history in reverse order
    const content = sortedContent.slice(0).reverse().map((post) =>
        <Card key={post.id}>
            <CardContent>
                <div className={classes.root} key={post.id} >
                    {/*<ExpansionPanel square expanded={true}>
                        */}
                    <ExpansionPanel expanded={expanded === `panel${post.id}`} onChange={handleChange(`panel${post.id}`)}>
                        <ExpansionPanelSummary
                            expandIcon={<MdExpandMore />}
                            aria-controls={`panel${post.id}bh-content`}
                            id="panel4bh-header">
                            <Box textAlign="left" m={1}>
                                <Typography display={'block'} gutterBottom={true}><span className={classes.secondaryHeading}>Company: </span>{post.companyName}</Typography>
                                {post.companysite ?
                                    <Typography gutterBottom={true} ><span className={classes.secondaryHeading}>URL: </span> <a href={post.companySite}>{post.companySite}</a></Typography>
                                    :
                                    ''}
                                <Typography gutterBottom={true}><span className={classes.secondaryHeading}> Role: </span>{post.role}</Typography>
                                <Typography gutterBottom={false}><span className={classes.secondaryHeading}>Duration: </span><Moment ago from={post.endDateUS}>{post.startDateUS}</Moment></Typography>
                                {post.teaser ?
                                    <CardContent>
                                        <Typography variant="body2" color="textSecondary" >
                                            {parse(post.teaser)}
                                        </Typography>
                                    </CardContent>
                                    :
                                    ''}

                            </Box>
                        </ExpansionPanelSummary>
                        <ExpansionPanelDetails>
                            {/* MAIN CONTENT LOOP */}
                            <Container>
                                < Card key={post.id}>
                                    <CardContent>
                                        <Typography variant="caption" color="textSecondary" >
                                            Start date: <Moment format="DD-MM-YYYY">{post.startDateUS}</Moment> | End date: <Moment format="DD-MM-YYYY">{post.endDateUS}</Moment>
                                        </Typography>
                                    </CardContent>
                                    {post.clientsWorkedWith ?
                                        <CardContent>
                                            <h3>Clients worked with:</h3>
                                            <Typography variant="caption" color="textPrimary" >
                                                <Grid container spacing={2}>
                                                    {post.clientsWorkedWith.map(client => (
                                                        <Grid item xs={6} sm={2} key={client}>
                                                            {client}
                                                        </Grid>
                                                    ))}
                                                </Grid>
                                            </Typography>
                                        </CardContent>
                                        : ''
                                    }

                                    {post.pmSkills ?
                                        <CardContent>
                                            <h3>PM (Waterfall/Agile) practices used include:</h3>
                                            <Typography variant="caption" color="textSecondary" >
                                                <Grid container spacing={2}>
                                                    {post.pmSkills.map(skill => (
                                                        <Grid item xs={6} sm={2} key={skill}>
                                                            <Typography variant={"caption"} color="textSecondary" >{skill}</Typography>
                                                        </Grid>
                                                    ))}
                                                </Grid>
                                            </Typography>
                                        </CardContent>
                                        : ''
                                    }

                                    {post.devSkills ?
                                        <CardContent>
                                            <h3>Development environment and tools used include:</h3>
                                            <Typography variant="body2" color="textPrimary" >
                                                <Grid container spacing={2}>
                                                    {post.devSkills.map(skill => (
                                                        <Grid item xs={6} sm={2} key={skill}>
                                                            <Typography variant={"caption"} color="textSecondary" >
                                                                {skill}</Typography>
                                                        </Grid>
                                                    ))}
                                                </Grid>
                                            </Typography>
                                        </CardContent>
                                        : ''
                                    }


                                    {post.respnsibilitiesAndDuties ?
                                        <CardContent>
                                            <h3>Some key responsibilities: </h3>
                                            <Typography variant="body2" color="textPrimary" >
                                                <Grid container spacing={2}>
                                                    {post.respnsibilitiesAndDuties.map(skill => (
                                                        <Grid item xs={6} sm={2} key={skill}>
                                                            <Typography variant={"caption"} color="textSecondary" >{skill}</Typography>

                                                        </Grid>
                                                    ))}
                                                </Grid>
                                            </Typography>
                                        </CardContent>
                                        : ''
                                    }


                                    {post.teamsWorkedWith ?
                                        <CardContent>
                                            <Typography variant="body2" color="textPrimary" >
                                                <h3>Worked closely with co-located teams from locations such as:</h3>
                                                <Grid container spacing={2}>
                                                    {post.teamsWorkedWith.map(teamLocation => (
                                                        <Grid item xs={6} sm={2} key={teamLocation}>
                                                            <Typography variant={"caption"} color="textSecondary" >{teamLocation}</Typography>

                                                        </Grid>
                                                    ))}
                                                </Grid>

                                            </Typography>
                                        </CardContent>
                                        :
                                        ''}


                                    {/*
                                {post.agileSkills ? <ul>{post.agileSkills.map(agileSkill => (<li key={agileSkill}>{agileSkill}</li>))}</ul> : ''}
                                {post.skills ? <ul>{post.skills.map(skill => (<li key={skill}>{skill}</li>))}</ul> : ''}

                                
                                {post.exampleSites ? <ul>{post.exampleSites.map(exampleSite => (<li key={exampleSite}>{exampleSite}</li>))}</ul> : ''}

                                {post.clientsWorkedWith ? <ul>{post.clientsWorkedWith.map(client => (<li key={client}>{client}</li>))}</ul> : ''}
                                {post.respnsibilitiesAndDuties ? <li>{post.respnsibilitiesAndDuties}</li> : ''}
                     */}
                                    {post.exampleSites ?
                                        <Typography className={classes.secondaryHeading}>
                                            Other sites examples:
                            <ul>
                                                {post.exampleSites.map(site => (
                                                    <li key={site}>{site}</li>
                                                ))}
                                            </ul>
                                        </Typography>
                                        :
                                        ''}

                                </Card >
                            </Container>
                            {/* END MAIN CONTENT LOOP */}

                        </ExpansionPanelDetails>
                    </ExpansionPanel >



                </div >
            </CardContent>
        </Card >
    );





    return (
        <>
            <h1>Previous employment</h1>
            {content}
        </>

    )
};

export default CareerHistory;