import { createMuiTheme } from "@material-ui/core/styles";

const sbPrimaryMain = "#2196f3";
const sbSecondaryMain = "#00bcd4";

export default createMuiTheme({
  palette: {
    primary: {
      light: "#4dabf5",
      main: `${sbPrimaryMain}`,
      dark: "#1769aa",
      contrastText: "#fff",
    },
    secondary: {
      main: `${sbSecondaryMain}`,
      contrastText: "#000",
    },
  },

  // palette: {
  //   primary: { 500: "#467fcf" },
  // },
  // titles: {
  //   fontFamily: "Raleway",
  //   color: theme.palette.secondary.dark,
  // },
  // titleLight: {
  //   fontFamily: "Raleway",
  //   color: theme.palette.secondary.main,
  // },
  // rootCard: {
  //   fontFamily: "Raleway",
  //   minWidth: 275,
  // },
  // currentStatus: {
  //   fontFamily: "Raleway",
  //   color: "#555",
  // },
  // icon: {
  //   height: "4em",
  //   width: "4em",
  //   [theme.breakpoints.down("xs")]: {
  //     height: "3em",
  //     width: "3em",
  //   },
  // },
  // listGridContainer: {
  //   display: "flex",
  //   alignItems: "center",
  //   flexWrap: "flex",
  // },
  // card: {
  //   margin: "10px",
  //   padding: "10px",
  // },
  // listGridContainer: {
  //   display: "flex",
  //   alignItems: "center",
  //   flexWrap: "flex",
  // },
  // root: {
  //   display: "flex",
  // },
  // details: {
  //   display: "flex",
  //   flexDirection: "column",
  // },
  // content: {
  //   flex: "1 0 auto",
  // },
  // rounded: {
  //   width: 180,
  //   height: 180,
  //   color: "#fff",
  //   backgroundColor: "primary",
  // },
  // root: {
  //   width: "100%",
  // },
  // heading: {
  //   fontSize: theme.typography.pxToRem(15),
  //   fontWeight: theme.typography.fontWeightRegular,
  //   flexBasis: "33.33%",
  //   flexShrink: 0,
  // },
  // secondaryHeading: {
  //   fontSize: theme.typography.pxToRem(15),
  //   // color: theme.palette.text.secondary,
  //   color: "grey",
  // },
  // /* Palette generated by Material Palette - materialpalette.com/indigo/blue-grey */
  // darkPrimaryColor: { background: "#303F9F" },
  // defaultPrimaryColor: { background: "#3F51B5" },
  // lightPrimaryColor: { background: "#C5CAE9" },
  // textPrimaryColor: { color: "#FFFFFF" },
  // accentColor: { background: "#607D8B" },
  // primaryTextColor: { color: "#212121" },
  // secondaryTextColor: { color: "#757575" },
  // dividerColor: { borderColor: "#BDBDBD" },
});
